global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'trading-services'
    static_configs:
      - targets: ['strategy-service:9100', 'risk-controller:9100', 'execution-engine:9100']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault:8200']
    scheme: https
    tls_config:
      insecure_skip_verify: true